name: Beginner Issue Template
description: Create a Beginner Issue for fairly new contributors to the Hiero Website
title: "[Beginner]: "
labels: ["beginner"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!
        This template is designed to help you create a Beginner-friendly issue: an easy, well-scoped task that helps fairly new contributors learn the codebase and build their skills.
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🐥 Beginner Friendly
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who have previously completed a Good First Issue in [Hiero Website](https://github.com/hiero-ledger/hiero-website) and are at a beginner level.
        We recognize that gaining confidence and building skills are equally important steps in the open-source contributor journey.
        The purpose of this issue—and others listed under [**Find a beginner issue**](https://github.com/hiero-ledger/hiero-website/issues?q=is%3Aissue%20state%3Aopen%20label%3Abeginner%20no%3Aassignee)—is to provide a supportive, low-pressure environment where you can learn, practice, and grow your contribution skills with confidence.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🐥 Beginner Issue Guidelines
        >
        > Beginner Issues are intended for contributors who are familiar with the project workflow and have **some programming or web development experience** and are wanting opportunities to build skills.
        > These issues may require **light investigation, interpretation of existing code, and some self-initiative**, but should remain **well-scoped with a clear intent**.
        >
        > **What we generally consider beginner issues:**
        >
        > - **Small, well-scoped updates to existing tests or lint rules**
        > - **Narrow changes or additions to website functionality** using common HTML/CSS/JS skills, such as:
        >   - Fixing a broken link or image
        >   - Updating alt text for accessibility
        >   - Correcting layout issues with simple CSS adjustments
        > - **Documentation improvements** in examples such as clarifying steps or adding missing details
        > - **Functional improvements to existing examples or snippets**:
        >   - Adding steps or variations to better demonstrate functionality
        >
        > **What we generally do NOT consider beginner issues:**
        > - Deep Hugo expertise or knowledge of advanced web development concepts
        > - Other CSS or frontend development experience
        > - Tasks better suited for Good First Issues (purely mechanical or fully guided changes)
        > - Changes to core website architecture or frameworks
        > - Work that requires deep knowledge across multiple areas of the codebase
        >
        > 📖 *For a more detailed explanation, refer to:  
        > [`docs/maintainers/beginner_issue_guidelines.md`](docs/maintainers/beginner_issue_guidelines.md).*

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE AND APPROACHABLE TO BEGINNER CONTRIBUTORS.
        ASSUME SUCH CONTRIBUTORS HAVE AT MOST BEGINNER-LEVEL KNOWLEDGE ABOUT WEB DEVELOPMENT AND THE HIERO WEBSITE.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
        SLIGHTLY CHALLENGE THEM TO ENCOURAGE LEARNING AND RESEARCH BUT MAKE SURE THE ISSUE IS STILL SIMPLE.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THEY ARE EASY TO FOLLOW.
        ADD LINKS TO RELEVANT DOCUMENTATION OR CODE SECTIONS IF POSSIBLE.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THEY ARE EASY TO FOLLOW.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist of requirements for merging a PR
      value: |
        To be able to merge a pull request for this issue, we need:
        - [ ] **Assignment:** You must be assigned to the issue, comment: `/assign` in the issue to get assigned
        - [ ] **Changelog Entry:** Correct changelog entry
        - [ ] **Signed commits:** commits must be DCO and GPG key signed
        - [ ] **All Tests Pass:** workflow checks like linting and integration tests must pass
        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        - [ ] **Assignment:** You must be assigned to the issue, comment: `/assign` in the issue to get assigned
        - [ ] **Fork, Branch and Work on the issue:** Create a copy of the repository, create a branch for the issue and solve the problem. See [Contributing guide](https://github.com/hiero-ledger/hiero-website/blob/main/CONTRIBUTING.md).
        - [ ] **DCO and GPG key sign each commit:** each commit must be -s and -S signed. See [Signing Guide](https://github.com/hiero-ledger/hiero-website/blob/main/docs/signing.md).
        - [ ] **Add a Changelog Entry:** follow [Changelog Entry Guide](https://github.com/hiero-ledger/hiero-website/blob/main/docs/changelog_entry.md).
        - [ ] **Push and Create a Pull Request:** Once your issue is resolved, push your changes and open a PR. See [Submit PR Training](https://github.com/hiero-ledger/hiero-website/tree/main/docs/training/workflow).
        - [ ] **You did it 🎉:** A maintainer will review and merge if approved.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide extra resources or context for contributors to solve this beginner issue
      value: |
        For more help:
        - Join our [Discord](https://github.com/hiero-ledger/hiero-website/blob/main/docs/discord.md))
