name: Advanced Issue Template
description: Create a high-impact issue for experienced contributors with deep familiarity with the Hiero Website codebase
title: "[Advanced]: "
labels: ["advanced"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 🚀

        We truly appreciate your interest in tackling an **Advanced issue**.

        This template is designed for work that requires **deep familiarity with the Hiero Website**
        and confidence making changes that may span multiple components or affect core behavior.

        The goal is to create issues for contributors who:
        - have strong familiarity with the Hiero Website internals
        - are comfortable reasoning about trade-offs and design decisions
        - can work independently with minimal guidance
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🧠 Advanced Contributors
      description: Who is this issue intended for?
      value: |
        This issue is intended for contributors who are already very familiar with the
        [Hiero Website](https://github.com/hiero-ledger/hiero-website) codebase and its architectural patterns.

        You should feel comfortable:
        - navigating multiple components across the site
        - understanding and modifying core abstractions (layouts, templates, build system)
        - reasoning about accessibility, performance, and backwards compatibility
        - updating or extending tests, examples, and documentation as needed
        - making changes that may affect public-facing behavior

        New developers should start with
        **Good First Issues** or **Beginner Issues** first.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > ### 🧭 What we consider an *Advanced Issue*
        >
        > This issue typically:
        >
        > - Requires **deep understanding of existing website design and behavior**
        > - May touch **core templates**, shared utilities, or cross-cutting concerns
        > - May involve **non-trivial refactors**, design changes, or behavior extensions
        > - Has **medium to high risk** if implemented incorrectly
        > - Requires careful consideration of **backwards compatibility and accessibility**
        > - May require updating **tests, examples, and documentation together**
        >
        > **What this issue is NOT:**
        > - A simple bug fix
        > - A narrowly scoped refactor
        > - A task solvable by following existing patterns alone
        >
        > 📖 Helpful references:
        > - `.github/guidelines_advanced_issues.md`

  - type: textarea
    id: problem
    attributes:
      label: 🐞 Problem Description
      description: |
        Describe the problem in depth.

        You may assume the reader:
        - understands the overall website architecture
        - can navigate and reason about multiple components
        - is comfortable reading and modifying core logic

        Clearly explain:
        - what the current behavior is
        - why it is insufficient or incorrect
        - which components or layers are involved
        - any relevant historical or design context
      value: |
        Describe the problem here.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed / Expected Solution
      description: |
        Describe the intended direction or design.

        This should include:
        - the high-level approach
        - any new abstractions or changes to existing ones
        - constraints (e.g. backwards compatibility, performance, accessibility)
        - known alternatives and why they were rejected (if applicable)

        A full design document is not required, but reasoning and intent should be clear.
      value: |
        Describe the proposed solution here.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 🧠 Implementation & Design Notes
      description: |
        Provide detailed technical guidance.

        This section is especially important for Advanced issues.

        Consider including:
        - specific modules or components involved
        - suggested refactoring strategy
        - migration or deprecation concerns
        - testing strategy
        - performance or security considerations
      value: |
        Add detailed implementation notes here.
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Define what "done" means for this issue
      value: |
        To merge this issue, the pull request must:

        - [ ] Fully address the problem and design goals described above
        - [ ] Maintain backwards compatibility unless explicitly approved otherwise
        - [ ] Follow existing architectural and coding conventions
        - [ ] Include comprehensive tests covering new and existing behavior
        - [ ] Update relevant examples and documentation
        - [ ] Pass all CI checks
        - [ ] Include a valid changelog entry
        - [ ] Use DCO and GPG-signed commits
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📚 Additional Context, Links, or Prior Art
      description: |
        Add any references that may help:
        - design docs
        - prior discussions
        - related issues or PRs
        - external references
      value: |
        Optional.
    validations:
      required: false
